# .github/workflows/ci-and-deploy.yml
name: Test & Deploy Quasar SPA

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

permissions:
  contents: write   # needed by peaceiris/actions-gh-pages to push to gh-pages

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  deploy:
    # Only run if tests succeeded AND the event is a push on master/main (not PR)
    needs: test
    if: >
      needs.test.result == 'success' &&
      github.event_name == 'push' &&
      (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest

    steps:
      - name: Download built SPA
        uses: actions/download-artifact@v4
        with:
          name: dist-spa
          path: dist/spa

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist/spa
          # optional: keep commit history on gh-pages
          # keep_files: true
